# mode(debug,test,release)
RunMode = "release"

# Whether to print configuration parameters at startup
PrintConfig = true

# Information about themselves
[Common]
# Wallet address
PeerId = "0x1B4b827703dc3545089fcee70F0e6e732BFF4413"
# Price - Price of services provided, unit: CSD/h, CSD It's our token
Price = 5000
# External service address
LocalAddr = ""
# External service port
LocalPort = 5092
## Cert Path
#CertPath = "./configs/fullchain.crt"
## Key Path
#KeyPath = "./configs/private.pem"

# p2p config
[P2p]
Enable = true
ServiceDiscoveryID = "cloudslit/provider"
ServiceDiscoverMode = "advertise" # advertise or announce
ServiceMetadataTopic = "cloudslit_provider_metadata"

[Log]
# level(1:fatal,2:error,3:warn,4:info,5:debug,6:trace)
Level = 4
# text、json
Format = "text"
# stdout、stderr、file
Output = "stdout"
OutputFile = "data/logger.log"
EnableHook = false
HookLevels = ["info", "warn", "error"]
# gorm、redis
Hook = "redis"
HookMaxThread = 1
HookMaxBuffer = 512

[LogRedisHook]
Addr = "127.0.0.1:6379"
Key = "log_key"
