version: '3.3'
services:
  provider:
    image: zhangshuainbb/cloudslit-provider:v0.0.7
    network_mode: host
    volumes:
      - "./config.toml:/root/config.toml"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 500M