version: '3.3'
services:
  icefiresqlite:
    image: taosheng205054/icefire-sqlite:latest
    restart: always
    ports:
      - "23306:23306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-P", "23306","-uroot","-p123456" ]
      timeout: 20s
      retries: 10
    networks:
      - cloudslit
    volumes:
      - ./sqlite.db:/app/sqlite.db

  cloudslit-backend:
    image: taosheng205054/cloudslit:latest
    restart: always
    environment:
      DOMAIN: 'dash.cloudslit.xyz'
      CS_MYSQL_HOST: 'icefiresqlite'
      CS_MYSQL_USER: 'root'
      CS_MYSQL_PASSWORD: '123456'
      CS_ACCOUNT: '0x828233e3908fB45d40baC6B2F19F8A239ab7ae7d'
    depends_on:
      icefiresqlite:
        condition: "service_healthy"
    networks:
      - cloudslit

networks:
  cloudslit:
    driver: bridge
