version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cloudslit
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    networks:
      - cloudslit
    volumes:
      - redis-data:/data

  root-ca-tls:
    image: zhangshuainbb/zaca:0.0.2
    command: [ "./zaca", "tls" ]
    volumes:
      - "./root_ca_config.json:/etc/zaca/config.json"
    environment:
      IS_ENV: 'test'
      IS_HTTP_CA_LISTEN: '0.0.0.0:8083'
      IS_SINGLECA_CONFIG_PATH: '/etc/zaca/config.json'
      IS_INFLUXDB_ENABLED: 'false'
      IS_KEYMANAGER_SELF_SIGN: 'true'
      IS_MYSQL_DSN: 'root:root@tcp(mysql:3306)/root_cap?charset=utf8mb4&parseTime=True&loc=Local'
    depends_on:
      - mysql
    networks:
      - cloudslit
    restart: always

  zaca-tls:
    image: zhangshuainbb/zaca:0.0.2
    command: [ "./zaca", "tls" ]
    ports:
      - "8081:8081"
    volumes:
      - "./ca_config.json:/etc/zaca/config.json"
    environment:
      IS_ENV: 'test'
      IS_SINGLECA_CONFIG_PATH: '/etc/zaca/config.json'
      IS_KEYMANAGER_UPPER_CA: "https://root-ca-tls:8083"
      IS_MYSQL_DSN: 'root:root@tcp(mysql:3306)/cap?charset=utf8mb4&parseTime=True&loc=Local'
      IS_OCSP_HOST: 'http://zaca-ocsp:8082'
    depends_on:
      - mysql
      - root-ca-tls
    networks:
      - cloudslit
    restart: always

  zaca-ocsp:
    image: zhangshuainbb/zaca:0.0.2
    command: [ "./zaca", "ocsp" ]
    ports:
      - "8082:8082"
    volumes:
      - "./ca_config.json:/etc/zaca/config.json"
    environment:
      IS_ENV: 'test'
      IS_SINGLECA_CONFIG_PATH: '/etc/zaca/config.json'
      IS_KEYMANAGER_UPPER_CA: "https://root-ca-tls:8083"
      IS_MYSQL_DSN: 'root:root@tcp(mysql:3306)/cap?charset=utf8mb4&parseTime=True&loc=Local'
    depends_on:
      - mysql
      - root-ca-tls
    networks:
      - cloudslit
    restart: always

  zaca-api:
    image: zhangshuainbb/zaca:0.0.2
    command: [ "./zaca", "api" ]
    ports:
      - "8080:8080"
    volumes:
      - "./ca_config.json:/etc/zaca/config.json"
    environment:
      IS_ENV: 'test'
      IS_SINGLECA_CONFIG_PATH: '/etc/zaca/config.json'
      IS_KEYMANAGER_UPPER_CA: "https://root-ca-tls:8083"
      IS_MYSQL_DSN: 'root:root@tcp(mysql:3306)/cap?charset=utf8mb4&parseTime=True&loc=Local'
    depends_on:
      - mysql
      - root-ca-tls
    networks:
      - cloudslit
    restart: always

  zta-portal:
    image: rovast/za-portal
    restart: always
    ports:
      - '180:80'
#      - '443:443'
    networks:
      - cloudslit
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  icefiresqlite:
    image: taosheng205054/icefire-sqlite:latest
    restart: always
    ports:
      - "23306:23306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-P", "23306","-uroot","-p123456" ]
      timeout: 20s
      retries: 10
    networks:
      - cloudslit
    volumes:
      - ./sqlite.db:/app/sqlite.db

  cloudslit-backend:
    image: taosheng205054/cloudslit:latest
    restart: always
    environment:
      DOMAIN: 'dash.cloudslit.xyz'
      CS_MYSQL_HOST: 'icefiresqlite'
      CS_MYSQL_USER: 'root'
      CS_MYSQL_PASSWORD: '123456'
      CS_ACCOUNT: '0x828233e3908fB45d40baC6B2F19F8A239ab7ae7d'
      CS_PRIVATE_KEY: 'xxx'
      CS_CONTRACT_TOKEN: 'xxx'
      CS_W3S_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDU4MUJkZEVGNTA3MDlmZjIzQzEwN0Q5YUU2NEVlMjc5M0IyMzk3NWMiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTY2NDc2MDM2MjUsIm5hbWUiOiJjbG91ZHNsaXQifQ.7iUZuCDn1SNn7CxuR_kdAWf9_PfpuJlqPmy7ZdB2x9U'
      CS_ETH_URL: 'https://ropsten.infura.io/v3'
      CS_ETH_PROJECTID: '45630f96f9d841679dc200a7c97763d2'
    depends_on:
      icefiresqlite:
        condition: "service_healthy"
    networks:
      - cloudslit

networks:
  cloudslit:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
