version: '3.3'
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379'
    networks:
      - cloudslit
    volumes:
      - redis-data:/data

  zta-portal:
    image: rovast/za-portal
    restart: always
    ports:
      - '180:80'
    #      - '443:443'
    networks:
      - cloudslit
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./portal_source:/usr/share/nginx/html
    depends_on:
      - cloudslit-backend

  icefiresqlite:
    image: taosheng205054/icefire-sqlite:latest
    restart: always
    ports:
      - "23306:23306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-P", "23306","-uroot","-p123456" ]
      timeout: 20s
      retries: 10
    networks:
      - cloudslit
    volumes:
      - ./db/sqlite.db:/app/db/sqlite.db

  cloudslit-backend:
    image: taosheng205054/cloudslit:v0.0.12
    restart: always
    environment:
      DOMAIN: 'https://dash.cloudslit.xyz'
      CS_REDIS_ADDR: 'redis:6379'
      CS_MYSQL_HOST: 'icefiresqlite'
      CS_MYSQL_USER: 'root'
      CS_MYSQL_PASSWORD: '123456'
#      CS_CA_SIGN_URL: 'https://zaca-tls:8081'
#      CS_CA_AUTH_KEY: '0739a645a7d6601d9d45f6b237c4edeadad904f2fce53625dfdd541ec4fc8134'
      CS_OAUTH2_CLIENT_ID: '736c3c420d6091f4cac0'
      CS_OAUTH2_CLIENT_SECRET: 'aeec3165d947ce121692ddf22ec77b7f2f0ec2bf'
      CS_ACCOUNT: '0x828233e3908fB45d40baC6B2F19F8A239ab7ae7d'
      CS_PRIVATE_KEY: 'xxx'
      CS_CONTRACT_TOKEN: 'xxx'
      CS_W3S_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDU4MUJkZEVGNTA3MDlmZjIzQzEwN0Q5YUU2NEVlMjc5M0IyMzk3NWMiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTY2NDc2MDM2MjUsIm5hbWUiOiJjbG91ZHNsaXQifQ.7iUZuCDn1SNn7CxuR_kdAWf9_PfpuJlqPmy7ZdB2x9U'
      CS_ETH_URL: 'https://ropsten.infura.io/v3'
      CS_ETH_PROJECTID: '45630f96f9d841679dc200a7c97763d2'
    depends_on:
      icefiresqlite:
        condition: "service_healthy"
      redis:
        condition: "service_started"
    networks:
      - cloudslit

networks:
  cloudslit:
    driver: bridge

volumes:
  redis-data:
